[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = [
    "tests",
]
norecursedirs = [
    ".git",
    "testing_config",
]
addopts = "--timeout=10 --cov-report=xml:coverage.xml --cov-report=term-missing --cov=hass_web_proxy_lib --cov-fail-under=100"

[tool.coverage.report]
exclude_also = [
    "raise NotImplementedError",
    "if TYPE_CHECKING:"
]
